version: '3'
services:
  db:
    container_name: db-solnuvem
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - portapi

  app:
    build: .
    container_name: nestjs-backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://solnuvem:RHxsbQago8iC59k99nkYW0G2z6m1Jasi@dpg-coa674n79t8c73ed8440-a.oregon-postgres.render.com/dbsolnuvem
    networks:
      - portapi
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start"
volumes:
  pgdata:

networks:
  portapi:
    driver: bridge